### ISSUE TITLE
Failed test test.unit.raid_device_test.TestRaidDevice.test_create_degraded_raid

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#28]
I've found a bug when you have a system with RAID devices:

```
FAIL: test.unit.raid_device_test.TestRaidDevice.test_create_degraded_raid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/repos/GH/kiwi-1/.tox/3.4/lib/python3.4/site-
packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/local/repos/GH/kiwi-1/.tox/3.4/lib/python3.4/site-
packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/local/repos/GH/kiwi-1/test/unit/raid_device_test.py", line 47, in 
test_create_degraded_raid
    '/dev/some-device', 'missing'
  File "/local/repos/GH/kiwi-1/.tox/3.4/lib/python3.4/site-
packages/mock/mock.py", line 948, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/local/repos/GH/kiwi-1/.tox/3.4/lib/python3.4/site-
packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 2, in raise_from
AssertionError: Expected call: run(['mdadm', '--create', '--run', '/dev/md0', 
'--level', '1', '--raid-disks', '2', '/dev/some-device', 'missing'])
Actual call: run(['mdadm', '--create', '--run', '/dev/md3', '--level', '1', 
'--raid-disks', '2', '/dev/some-device', 'missing'])
```

**Comment by tomschr** [comment]
This is fixed with commit a0102cddbfe262a35a7ebe5ed5f4a452bdddebd6, so closing
