### ISSUE TITLE
Exception when a commandline repo has no priority

### ISSUE THREAD

**Issue by mlschroe** [SUSE/kiwi#408]
## Problem description
Using --add-repo to add a repo without a priority results in an exception because the None value cannot be converted into an integer:
```
Traceback (most recent call last):
  File "/usr/bin/kiwi", line 9, in <module>
    load_entry_point('kiwi==9.8.1', 'console_scripts', 'kiwi-ng-3')()
  File "/usr/lib/python3.4/site-packages/kiwi/kiwi.py", line 54, in main 
    App()
  File "/usr/lib/python3.4/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/lib/python3.4/site-packages/kiwi/tasks/system_build.py", line 157, in process
    *self.quintuple_token(add_repo)
  File "/usr/lib/python3.4/site-packages/kiwi/xml_state.py", line 1286, in add_repository
    imageinclude=repo_imageinclude
  File "/usr/lib/python3.4/site-packages/kiwi/xml_parse.py", line 2135, in __init__
    self.priority = _cast(int, priority)
  File "/usr/lib/python3.4/site-packages/kiwi/xml_parse.py", line 682, in _cast
    return typ(value)
ValueError: invalid literal for int() with base 10: ''
```

Note that kiwi-compat creates such --add-repo calls when there is no --add-repopriority used, like with osc.

**Comment by davidcassany** [comment]
verified, working on that one
